### ISSUE TITLE
Category image enlarge the column

### ISSUE THREAD

**Issue by glatorg** [openppg/discourse-simple-theme#1]
Because of max-height of the category image.
To avoid pay attention at the aspect ratio images should be put the image as background of a div and give some css properties:
` {
    background-image: url(//discourse-openppg...png);
    height: 150px;
    background-size: contain;
    background-repeat: no-repeat;
}`

<img width="756" alt="screen shot 2018-01-21 at 23 53 24" src="https://user-images.githubusercontent.com/24441747/35200043-623ec7a2-ff07-11e7-9ba4-785421c0c5c7.png">

**Comment by zjwhitehead** [comment]
Fixed with https://github.com/openppg/discourse-simple-theme/commit/ed329b0dc7aa9f74e0faed3f62f09ce52534bed1
